:sonar-project-id: keithpaterson_go-tools
:sonar-badges: https://sonarcloud.io/api/project_badges/measure?project={sonar-project-id}
:img-quality-gate: {sonar-badges}&metric=alert_status
:img-coverage: {sonar-badges}&metric=coverage
:img-maintainability: {sonar-badges}&metric=sqale_rating
:img-security-rating: {sonar-badges}&metric=security_rating
:img-reliability: {sonar-badges}&metric=reliability_rating
:img-techdebt: {sonar-badges}&metric=sqale_index
:uri-analysis: https://sonarcloud.io/summary/new_code?id={sonar-project-id}

= Personal Go tools

A few things I seem to keep repeating.

Dive into the packages for more detail; this is just a simple summary.

== Project Health

[.text-center]

|===
|image:{img-quality-gate}[Quality Gate,link={uri-analysis}]|image:{img-coverage}[Coverage,link={uri-analysis}] |image:{img-maintainability}[Maintainability,link={uri-analysis}]

|image:{img-reliability}[Reliability,link={uri-analysis}]
|image:{img-security-rating}[Security Rating,link={uri-analysis}]
|image:{img-techdebt}[Technical Debt,link={uri-analysis}]

|===

== Importing

To import this project you need this command-line:
```
go get github.com/keithpaterson/go-tools
```

== Overview

=== package env

==== Setup

Simplifies configuring (and un-configuring) your environment variables.
This is quite useful for testing, particularly with web services, so that you can
easily and reliably adjust the runtime environment during test without having
to deal with complicated scripting.

Example:

```
// build your environment  (add `$FOO` with value "foo", and remove `$BAR`)
var (
  myEnv := env.New().Set("FOO", "foo").Unset("BAR")
)

func myFunc() {
  // apply the environment and revert on exit
  origEnv := myEnv.Apply()
  defer origEnv.Apply()

  ... // your code goes here

  // when the function exits, the environment reverts to its original state
}
```

==== Tag parser

Allows you to use \`envp:"name"\` tags with your structs to read values from environment
variables.

For Example:
```
type MyStruct struct {
  Foo string `envp:"FOO"`
  Bar int    `envp:"BAR,default=100"`
}

func myFunc() {
  origEnv := env.New().Set("FOO", "blue").Unset("BAR").Apply()
  defer origEnv.Apply()

  var err error
  var mine MyStruct
  if err = env.ResolveEnv(&mine); err != nil {
    panic("something went wrong")
  }

  // result:
  // mine {
  //   Foo: "blue",
  //   Bar: 100,
  // }
}
```

=== package resolver

Provides a customizable text tokenizer.

Tokens are specified with the pattern `${type:value}` and are resolved via the
provided resolvers.

Default resolver types include:

- `date`, `time`, `datetime`, `epoch` for date formatting and manipulation
  (e.g. you can specify a date like "now + 1D" to get "now" plus a day)
- `env` looks up environment variables
- `prop` looks up values contained in a properties collection

You can implement custom resolvers using the `Resolver` interface and
the `ResolverImpl` base struct,

